using Microsoft.Extensions.DependencyInjection;
using Microsoft.FeatureManagement;
using OneOf;
using OneOf.Types;

namespace FeatureSlice.NewDispatcher;

public static class NotGenerated
{
    public sealed record Disabled();

    //Generators would be helpfull for Pipelines
    public interface IFeatureSlice<TSelf, TRequest, TResponse>
        where TSelf : class, IFeatureSlice<TSelf, TRequest, TResponse>
    {
        public string FeatureName { get; }

        public Task<TResponse> Handle(TRequest request);

        public interface IDispatcher
        {
            public Task<OneOf<TResponse, Disabled>> Send(TRequest request);
        }

        internal class Dispatcher : IDispatcher
        {
            private readonly TSelf _feature;
            private readonly IFeatureManager _featureManager;
            private readonly string _featureName;

            public Dispatcher(TSelf feature, IFeatureManager featureManager)
            {
                _feature = feature;
                _featureManager = featureManager;
                _featureName = feature.FeatureName;
            }

            public async Task<OneOf<TResponse, Disabled>> Send(TRequest request)
            {
                if(await _featureManager.IsEnabledAsync(_featureName))
                {
                    return new Disabled();    
                }

                return await _feature.Handle(request);
            }
        }

        public static void Register<TImplementation>(IServiceCollection services)
            where TImplementation : class, TSelf
        {
            services.AddFeatureManagement();
            services.AddSingleton<TSelf, TImplementation>();
        }
    }

    public interface IExampleFeature : IFeatureSlice<IExampleFeature, IExampleFeature.Request, IExampleFeature.Response>
    {
        public sealed record Request();
        public sealed record Response();

        internal sealed class Feature : IExampleFeature
        {
            public string FeatureName => "ExampleFeature";

            public Task<Response> Handle(Request request)
            {
                throw new NotImplementedException();
            }
        }
    }
}

public static class Generated
{
    public sealed record Disabled();

    public interface IFeatureSlice<TRequest, TResponse>
    {
        public static abstract string FeatureName { get; }

        public Task<TResponse> Handle(TRequest request);

        public interface IDispatcher
        {
            public Task<OneOf<TResponse, Disabled>> Send(TRequest request);
        }

        public delegate Task<OneOf<TResponse, Disabled>> Dispatch(TRequest request);
    }

    public interface IPipeline<TRequest, TResponse>
    {
        public delegate TResponse Next(TRequest request);

        public TResponse Handle(TRequest request, Next next);
    }

    public sealed class ExamplePipeline<TRequest, TResponse> : IPipeline<TRequest, TResponse>
        where TRequest : class
        where TResponse : class
    {
        public TResponse Handle(TRequest request, IPipeline<TRequest, TResponse>.Next next)
        {
            return next(request);
        }
    }

    public sealed partial class ExampleFeature : IFeatureSlice<ExampleFeature.Request, ExampleFeature.Response>
    {
        public sealed record Request();
        public sealed record Response();
        public static string FeatureName => "ExampleFeature";

        public ExampleFeature(Dependency dependency)
        {
        }

        public Task<Response> Handle(Request request)
        {
            throw new NotImplementedException();
        }
    }


    //AutoGenerated
    public partial class ExampleFeature
    {
        public interface IDispatcher : IFeatureSlice<Request, Response>.IDispatcher
        {
        }

        public delegate Task<OneOf<Response, Disabled>> Dispatch(Request request);

        internal sealed class Dispatcher : IDispatcher
        {
            private readonly ExampleFeature _feature;
            private readonly IFeatureManager _featureManager;

            public Dispatcher(ExampleFeature feature, IFeatureManager featureManager)
            {
                _feature = feature;
                _featureManager = featureManager;
            }

            public async Task<OneOf<Response, Disabled>> Send(Request request)
            {
                if(await _featureManager.IsEnabledAsync(FeatureName))
                {
                    return new Disabled();    
                }

                return await _feature.Handle(request);
            }
        }

        public static void Register(IServiceCollection services)
        {
            services.AddFeatureManagement();
            services.AddSingleton<ExampleFeature>();
            services.AddSingleton<IDispatcher, Dispatcher>();
        }

        public static void RegisterDispatch(IServiceCollection services)
        {
            services.AddFeatureManagement();
            services.AddSingleton<ExampleFeature>();
            services.AddSingleton<Dispatcher>();
            services.AddSingleton<Dispatch>(provider => provider.GetRequiredService<Dispatcher>().Send);
        }
    }
}

public class Dependency
{
    public void Register(IServiceCollection services)
    {
        services.AddSingleton<Dependency>();
        Generated.ExampleFeature.Register(services);
        Generated.ExampleFeature.RegisterDispatch(services);
    }

    public async Task Run(
        NotGenerated.IExampleFeature.IDispatcher notDispatcher,
        Generated.ExampleFeature.IDispatcher genDispatcher,
        Generated.ExampleFeature.Dispatch dispatch)
    {
        await notDispatcher.Send(new NotGenerated.IExampleFeature.Request());
        await genDispatcher.Send(new Generated.ExampleFeature.Request());
        await dispatch(new Generated.ExampleFeature.Request());
    }
}



//Auto generate Dependencies code
public sealed partial class DependencyChecker :
    IDependencyProvide<Dependency>,
    IDependencyProvide<IFeatureManager>,
    IDependencyProvide<Generated.ExampleFeature>,
    IDependencyProvide<Generated.ExampleFeature.IDispatcher>,
    IDependencyProvide<Generated.ExampleFeature.Dispatcher>,
    IDependencyProvide<Generated.ExampleFeature.Dispatch>
{
}

public sealed partial class DependencyChecker :
    IDependencyRequire<Dependency, DependencyChecker>,
    IDependencyRequire<Generated.ExampleFeature, DependencyChecker>,
    IDependencyRequire<IFeatureManager, DependencyChecker>,
    IDependencyRequire<Generated.ExampleFeature.Dispatcher, DependencyChecker>,
    IDependencyRequire<Generated.ExampleFeature.Dispatch, DependencyChecker>
{
}

public interface IDependencyProvide<T>
{
}

public interface IDependencyRequire<T, TProvider>
    where TProvider : IDependencyProvide<T>
{
}

public sealed partial class DependencyChecker
{
}