using Microsoft.Extensions.DependencyInjection;
using Microsoft.FeatureManagement;
using OneOf;

namespace FeatureSlice.Dispatch;

public interface IFeatureSlice<TRequest, TResponse> : IMethod<TRequest, Task<TResponse>>
{
}

public abstract class FeatureSlice<TSelf, TRequest, TResponse> : IFeatureSlice<TRequest, TResponse>, IRegistrable
    where TSelf : FeatureSlice<TSelf, TRequest, TResponse>, IFeatureName
{
    public abstract Task<TResponse> Handle(TRequest request);

    public delegate Task<OneOf<TResponse, Disabled>> Dispatcher(TRequest request);

    public static async Task<OneOf<TResponse, Disabled>> Dispatch(TRequest request, TSelf self, IFeatureManager featureManager, IReadOnlyList<IFeatureSlice<TRequest, TResponse>.IPipeline> pipelines)
    {
        if(await featureManager.IsEnabledAsync<TSelf>())
        {
            return new Disabled();    
        }

        return await pipelines.RunPipeline(request, self.Handle);
    }

    public static void Register(IApplicationSetup setup)
    {
        setup.Services.AddFeatureManagement();
        setup.Services.AddSingleton<TSelf>();
        setup.Services.AddSingleton<Dispatcher>(provider => request => Dispatch(
            request,
            provider.GetRequiredService<TSelf>(),
            provider.GetRequiredService<IFeatureManager>(),
            provider.GetServices<IFeatureSlice<TRequest, TResponse>.IPipeline>().ToList())
        );
    }
}

//Example SourceGenerated approach
internal static class Example
{
    private sealed record Request(); 
    private sealed record Response();

    private partial class Feature : IFeatureSlice<Request, Response>
    {
        public static string FeatureName => "test";

        public Task<Response> Handle(Request request)
        {
            throw new NotImplementedException();
        }
    }

    //AutoGenerated
    private partial class Feature : IRegistrable, IFeatureName
    {
        public delegate Task<OneOf<Response, Disabled>> Dispatcher(Request request);

        public static async Task<OneOf<Response, Disabled>> Dispatch(Request request, Feature self, IFeatureManager featureManager, IReadOnlyList<IFeatureSlice<Request, Response>.IPipeline> pipelines)
        {
            if(await featureManager.IsEnabledAsync<Feature>())
            {
                return new Disabled();
            }

            return await pipelines.RunPipeline(request, self.Handle);
        }

        public static void Register(IApplicationSetup setup)
        {
            setup.Services.AddFeatureManagement();
            setup.Services.AddSingleton<Feature>();
            setup.Services.AddSingleton<Dispatcher>(provider => request => Dispatch(
                request,
                provider.GetRequiredService<Feature>(),
                provider.GetRequiredService<IFeatureManager>(),
                provider.GetServices<IFeatureSlice<Request, Response>.IPipeline>().ToList())
            );
        }
    }
}